# Generated by Django 4.2.4 on 2023-11-26 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_and_month",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_year_month",
                                message="Year and month should be in YYYY-MM format.",
                                regex="^\\d{4}-\\d{2}$",
                            )
                        ],
                    ),
                ),
                ("opinion", models.TextField(max_length=999)),
            ],
        ),
    ]
