# Generated by Django 4.2.4 on 2023-10-09 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("factors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SegType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("is_office", models.BooleanField(default=False)),
                (
                    "g_examination",
                    models.CharField(
                        choices=[
                            ("다른병원에서 일반검진", "다른병원에서 일반검진"),
                            ("고대에서 일반검진", "고대에서 일반검진"),
                            ("센트럴에서 일반검진", "센트럴에서 일반검진"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "s_examination",
                    models.CharField(
                        choices=[
                            ("다른병원에서 일반검진", "다른병원에서 일반검진"),
                            ("고대에서 일반검진", "고대에서 일반검진"),
                            ("센트럴에서 일반검진", "센트럴에서 일반검진"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_night", models.BooleanField(default=False)),
                ("join_date", models.DateField()),
                ("is_complete", models.BooleanField(default=False)),
                ("examination_date", models.DateField()),
                (
                    "factors",
                    models.ManyToManyField(related_name="factors", to="factors.factor"),
                ),
                (
                    "seg_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staffs",
                        to="staffs.segtype",
                    ),
                ),
            ],
        ),
    ]
