# Generated by Django 4.2.4 on 2023-10-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staffs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="g_examination",
            field=models.CharField(
                choices=[
                    ("다른병원에서 일반검진", "다른병원에서 일반검진"),
                    ("고대에서 일반검진", "고대에서 일반검진"),
                    ("센트럴에서 일반검진", "센트럴에서 일반검진"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="s_examination",
            field=models.CharField(
                choices=[
                    ("다른병원에서 일반검진", "다른병원에서 일반검진"),
                    ("고대에서 일반검진", "고대에서 일반검진"),
                    ("센트럴에서 일반검진", "센트럴에서 일반검진"),
                ],
                max_length=100,
            ),
        ),
    ]
