# Generated by Django 4.2.4 on 2023-10-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("staffs", "0001_initial"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="staffs",
            field=models.ManyToManyField(related_name="companys", to="staffs.staff"),
        ),
    ]
